Update CI Alpine version
The Rust 1.70 build fails on new Alpine due to the musl upgrade and its
file api changes:

undefined reference to `fstat64'
undefined reference to `lseek64'

etc. So now do that build on Debian